/* eslint-disable no-unused-vars */
export const apiToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VybmFtZSI6ImhlbnJ5dHJhbjAxMjU5OSIsIkNvbWlkIjpudWxsLCJSb2xlaWQiOm51bGwsImlzcyI6InRtYXBpIiwic3ViIjoiaGVucnl0cmFuMDEyNTk5IiwiYXVkIjpbIiJdLCJpYXQiOjE3MTI1NTY4MDV9.OoBQLtZ-EiMFHmCimbGlBOJymPgtc9W515Qo6kGxqcA";
